services:
  mysql:
    image: mysql:8.0
    container_name: mysql-test-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-test-data:/var/lib/mysql

volumes:
  mysql-test-data: